const game=document.querySelector('#game'),board=document.querySelector('#board'),player=document.querySelector('#player'),goal=document.querySelector('#goal'),message=document.querySelector('#message'),action=document.querySelector('#action'),scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best'),tagline=document.querySelector('#tagline'),help=document.querySelector('#help');
const order=['nathalia','esteban','alison'];let worldIndex=0,world=order[0],playing=false,score=0,best=+localStorage.getItem('crashChickenBest')||0,objects=[],pos={x:50,y:8},last=0,frame,spawn=0,snake=[],food=null,dir={x:1,y:0},nextDir=dir,snakeClock=0;bestEl.textContent=best;
const names={nathalia:'MUNDO 1 · NATHALIA',esteban:'MUNDO 2 · ESTEBAN',alison:'MUNDO 3 · ALISON'};
function setScore(){score=Math.max(0,score);scoreEl.textContent=score}function clearBoard(){board.replaceChildren();objects=[]}function rectHit(a,b,p=8){return a.left<b.right-p&&a.right>b.left+p&&a.top<b.bottom-p&&a.bottom>b.top+p}
function makeRoad(){board.innerHTML='<div class="finish">¡LLEGADA!</div><div class="road"></div><div class="grass"></div><div class="road"></div><div class="grass"></div><div class="road"></div><div class="grass"></div><div class="road"></div><div class="start">INICIO</div>';for(let i=0;i<7;i++){let e=document.createElement('div');e.className='car';e.innerHTML='<img src="assets/car.png" alt="Auto">';e.style.left=(i%2?68:8)+'%';e.style.top=(12+i*10)+'%';e.dataset.speed=(i%2?-1:1)*(14+i*2);board.append(e);objects.push({e,x:parseFloat(e.style.left),y:12+i*10,s:+e.dataset.speed})}}
function startNathalia(){world='nathalia';tagline.textContent=names[world];help.textContent='Cruza la carretera. Usa flechas, WASD o desliza.';game.className='road-world';goal.style.display='none';player.style.display='block';player.querySelector('img').src='assets/chicken-go.png';clearBoard();makeRoad();pos={x:50,y:8};draw();playing=true}
function startEsteban(){world='esteban';tagline.textContent=names[world];help.textContent='El cielo tiembla: esquiva los objetos y llega al portal rojo.';game.className='fall-world';goal.style.display='grid';goal.textContent='¡LLEGADA!';player.style.display='block';clearBoard();pos={x:50,y:8};spawn=.2;draw();playing=true}
function startAlison(){world='alison';tagline.textContent=names[world];help.textContent='Recoge huevos y haz crecer a Snake Chicken.';game.className='snake-world';goal.style.display='none';player.style.display='none';clearBoard();snake=[{x:4,y:4},{x:3,y:4},{x:2,y:4}];dir={x:1,y:0};nextDir=dir;makeFood();drawSnake();playing=true}
function startCurrent(){score=0;setScore();world==='nathalia'?startNathalia():world==='esteban'?startEsteban():startAlison();message.classList.remove('show','crash');game.focus();cancelAnimationFrame(frame);last=performance.now();frame=requestAnimationFrame(loop)}
function draw(){player.style.left=`calc(${pos.x}% - 29px)`;player.style.bottom=pos.y+'%'}function makeFood(){food={x:Math.floor(Math.random()*11)+1,y:Math.floor(Math.random()*9)+1};drawSnake()}
function drawSnake(){board.innerHTML='';snake.forEach((part,i)=>{let e=document.createElement('div');e.className='snake-part'+(i===0?' snake-head':'');e.style.left=(part.x*8)+'%';e.style.top=(part.y*10)+'%';board.append(e)});if(food){let e=document.createElement('div');e.className='egg';e.style.left=(food.x*8)+'%';e.style.top=(food.y*10)+'%';e.innerHTML='<img src="assets/chicken-egg-special.png" alt="Huevo">';board.append(e)}}
function spawnFalling(){let e=document.createElement('div');e.className=Math.random()>.45?'falling car-falling':'falling corn-falling';e.innerHTML=e.classList.contains('car-falling')?'<img src="assets/car.png" alt="Objeto">':'<img src="assets/corn-toxic.png" alt="Maíz tóxico">';board.append(e);objects.push({e,x:4+Math.random()*92,y:-10,s:24+Math.random()*25})}
function finish(){playing=false;cancelAnimationFrame(frame);if(world==='alison'){score+=10;setScore();return show('¡Completaste los 3 mundos!','Llegaste al final. +10 puntos.','JUGAR DE NUEVO',false)}let next=order.indexOf(world)+1;show('¡Mundo completado!',`Preparando ${names[order[next]]}...`,'',false);setTimeout(()=>{world=order[next];startCurrent()},900)}
function crash(){playing=false;cancelAnimationFrame(frame);score=Math.max(0,score);setScore();show('¡Crash!',`Conseguiste ${score} puntos.`,'REPETIR MUNDO',true)}function show(t,p,b,c){message.classList.toggle('crash',c);message.querySelector('h2').textContent=t;message.querySelector('p').textContent=p;action.textContent=b;action.style.display=b?'inline-block':'none';message.classList.add('show')}
function loop(now){if(!playing)return;let dt=Math.min((now-last)/1000,.05);last=now;if(world==='nathalia'){objects.forEach(o=>{o.x+=o.s*dt;o.e.style.left=o.x+'%';if(o.x>105)o.x=-15;if(o.x<-15)o.x=105});let r=player.getBoundingClientRect();if(objects.some(o=>rectHit(r,o.e.getBoundingClientRect(),16)))return crash();if(pos.y>=88)return finish()}else if(world==='esteban'){game.classList.toggle('shake',Math.sin(now/75)>.2);spawn-=dt;if(spawn<=0){spawnFalling();if(Math.random()>.45)spawnFalling();spawn=Math.max(.2,.65-(now-last)/1000)}objects.forEach(o=>{o.y+=o.s*dt;o.e.style.left=o.x+'%';o.e.style.top=o.y+'%'});let r=player.getBoundingClientRect();if(objects.some(o=>rectHit(r,o.e.getBoundingClientRect(),10)))return crash();objects=objects.filter(o=>o.y<110);if(pos.y>=88)return finish();score+=Math.floor(dt*5);setScore()}else{snakeClock+=dt;if(snakeClock<.18)return frame=requestAnimationFrame(loop);snakeClock=0;let head={x:snake[0].x+nextDir.x,y:snake[0].y+nextDir.y};dir=nextDir;if(head.x<0||head.x>11||head.y<0||head.y>9||snake.some(p=>p.x===head.x&&p.y===head.y))return crash();snake.unshift(head);if(head.x===food.x&&head.y===food.y){score+=10;setScore();makeFood()}else snake.pop();drawSnake();if(score>=100)return finish()}frame=requestAnimationFrame(loop)}
function move(k){if(!playing)return;if(world==='alison'){let d={ArrowUp:{x:0,y:-1},w:{x:0,y:-1},W:{x:0,y:-1},ArrowDown:{x:0,y:1},s:{x:0,y:1},S:{x:0,y:1},ArrowLeft:{x:-1,y:0},a:{x:-1,y:0},A:{x:-1,y:0},ArrowRight:{x:1,y:0},d:{x:1,y:0},D:{x:1,y:0}}[k];if(d&&d.x+dir.x!==0||d&&d.y+dir.y!==0)nextDir=d;return}let s=world==='esteban'?8:10;if(['ArrowUp','w','W'].includes(k))pos.y=Math.min(88,pos.y+s);if(['ArrowDown','s','S'].includes(k))pos.y=Math.max(8,pos.y-s);if(['ArrowLeft','a','A'].includes(k))pos.x=Math.max(4,pos.x-s);if(['ArrowRight','d','D'].includes(k))pos.x=Math.min(96,pos.x+s);draw()}
document.addEventListener('keydown',e=>{if(/Arrow|^[wasdWASD]$/.test(e.key))e.preventDefault();if(e.key.toLowerCase()==='r')startCurrent();else move(e.key)});action.onclick=startCurrent;let touch=null;game.addEventListener('touchstart',e=>{touch=e.touches[0];e.preventDefault()},{passive:false});game.addEventListener('touchend',e=>{if(!touch)return;let t=e.changedTouches[0],dx=t.clientX-touch.clientX,dy=t.clientY-touch.clientY;touch=null;if(Math.max(Math.abs(dx),Math.abs(dy))<18)return move('ArrowUp');move(Math.abs(dx)>Math.abs(dy)?dx>0?'ArrowRight':'ArrowLeft':dy>0?'ArrowDown':'ArrowUp');e.preventDefault()},{passive:false});startCurrent();
