const game=document.querySelector('#game'),chicken=document.querySelector('#chicken'),scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best'),message=document.querySelector('#message'),play=document.querySelector('#play'),help=document.querySelector('#help');let playing=false,world=1,score=0,best=+localStorage.getItem('crashChickenBest')||0,pos={x:50,y:4},cars=[],corns=[],falling=[],last=0,frame,spawnTimer=0,world2Time=0;const lanes=[{top:10,d:1,s:12,h:[275,190]},{top:40,d:-1,s:17,h:[35,195]},{top:70,d:1,s:22,h:[110,260,45]}];bestEl.textContent=best;
function draw(){chicken.style.left=`calc(${pos.x}% - 29px)`;chicken.style.bottom=pos.y+'%'}function makeCars(){document.querySelectorAll('.car').forEach(x=>x.remove());cars=lanes.flatMap((l,n)=>(n===2?[0,36,75]:[10,66]).map((x,i)=>{let e=document.createElement('div');e.className='car';e.innerHTML='<img src="car.png" alt="Auto">';e.style.setProperty('--hue',`${l.h[i]}deg`);game.append(e);return{e,n,x}}))}function makeCorn(){document.querySelectorAll('.corn').forEach(x=>x.remove());corns=[{x:30,t:45},{x:73,t:75}].map(c=>{let e=document.createElement('div');e.className='corn';e.style.left=c.x+'%';e.style.top=c.t+'%';e.innerHTML='<img src="corn.png" alt="Maíz">';game.append(e);return{e,got:false}})}function clean(){document.querySelectorAll('.falling').forEach(x=>x.remove());falling=[]}function show(t,p,b,c=false){message.classList.toggle('crash',c);message.querySelector('h2').textContent=t;message.querySelector('p').textContent=p;play.textContent=b;message.classList.add('show')}
function world1(){world=1;game.classList.remove('world-two','shaking');help.textContent='Recoge maíz (+25). Pulsa R para reiniciar.';clean();score=0;pos={x:50,y:4};scoreEl.textContent=0;draw();makeCars();makeCorn();message.classList.remove('show','crash');playing=true;last=performance.now();game.focus();cancelAnimationFrame(frame);frame=requestAnimationFrame(loop)}function world2(){world=2;game.classList.add('world-two');help.textContent='¡El cielo tiembla! Muévete a los lados para esquivar lo que cae.';document.querySelectorAll('.car,.corn').forEach(x=>x.remove());clean();pos={x:50,y:8};world2Time=0;spawnTimer=0;draw();message.classList.remove('show','crash');playing=true;last=performance.now();game.focus();cancelAnimationFrame(frame);frame=requestAnimationFrame(loop)}function hit(a,b,p=10){return a.left<b.right-p&&a.right>b.left+p&&a.top<b.bottom-p&&a.bottom>b.top+p}function finish(){playing=false;cancelAnimationFrame(frame);show('¡Mundo 1 superado!','El suelo tiembla... algo está cayendo del cielo.','ENTRAR AL MUNDO 2')}function end(crash=true){playing=false;cancelAnimationFrame(frame);game.classList.remove('shaking');if(score>best){best=score;localStorage.setItem('crashChickenBest',best);bestEl.textContent=best}if(world===1&&!crash)return finish();show(crash?'¡Crash!':'¡Sobreviviste!',`Conseguiste ${score} puntos.`,world===2?'REPETIR MUNDO 2':'REINTENTAR',crash)}
function spawn(){let e=document.createElement('div');e.className='falling '+(Math.random()>.45?'falling-corn':'falling-car');e.innerHTML=e.classList.contains('falling-car')?'<img src="car.png" alt="Objeto que cae">':'<img src="corn.png" alt="Objeto que cae">';game.append(e);falling.push({e,x:4+Math.random()*92,y:-12,speed:24+Math.random()*20+world2Time*1.5,spin:Math.random()*80-40})}function loop(now){if(!playing)return;let dt=Math.min((now-last)/1000,.05);last=now;if(world===1){cars.forEach(c=>{let l=lanes[c.n];c.x+=l.d*l.s*dt;if(l.d===1&&c.x>108)c.x=-15;if(l.d===-1&&c.x<-15)c.x=108;c.e.style.left=c.x+'%';c.e.style.top=l.top+7+'%';c.e.style.transform=l.d<0?'scaleX(-1)':''});let r=chicken.getBoundingClientRect();if(cars.some(c=>hit(r,c.e.getBoundingClientRect(),16)))return end();corns.forEach(c=>{if(!c.got&&hit(r,c.e.getBoundingClientRect(),7)){c.got=true;c.e.classList.add('collected');score+=25;scoreEl.textContent=score}})}else{world2Time+=dt;spawnTimer-=dt;game.classList.toggle('shaking',Math.sin(now/85)>.25);if(spawnTimer<=0){spawn();spawnTimer=Math.max(.28,.8-world2Time/80)}falling.forEach(o=>{o.y+=o.speed*dt;o.e.style.left=o.x+'%';o.e.style.top=o.y+'%';o.e.style.transform=`rotate(${o.y*o.spin}deg)`});let r=chicken.getBoundingClientRect();if(falling.some(o=>hit(r,o.e.getBoundingClientRect(),12)))return end();falling=falling.filter(o=>o.y<110);score+=Math.floor(dt*5);scoreEl.textContent=score}frame=requestAnimationFrame(loop)}
function move(k){if(!playing)return;let s=world===2?8:10;if(['ArrowUp','w','W'].includes(k))pos.y=Math.min(world===2?88:91,pos.y+s);if(['ArrowDown','s','S'].includes(k))pos.y=Math.max(world===2?8:4,pos.y-s);if(['ArrowLeft','a','A'].includes(k))pos.x=Math.max(4,pos.x-s);if(['ArrowRight','d','D'].includes(k))pos.x=Math.min(96,pos.x+s);if(world===1){score=Math.max(score,Math.floor((pos.y-4)/10)*10);scoreEl.textContent=score;if(pos.y>=91)end(false)}draw()}function start(){if(world===1&&message.querySelector('h2').textContent==='¡Mundo 1 superado!')world2();else if(world===2)world2();else world1()}document.addEventListener('keydown',e=>{if(/Arrow|^[wasdWASD]$/.test(e.key))e.preventDefault();if(e.key.toLowerCase()==='r')world1();else move(e.key)});play.onclick=start;world1();
// La llegada al primer mundo continúa automáticamente al siguiente escenario.
function finish(){world2()}
function world2(){world=2;game.classList.add('world-two');help.textContent='Llega al portal rojo sin que te golpeen los objetos.';document.querySelectorAll('.car,.corn').forEach(x=>x.remove());clean();score=0;scoreEl.textContent=score;pos={x:50,y:8};world2Time=0;spawnTimer=.25;draw();message.classList.remove('show','crash');playing=true;last=performance.now();game.focus();cancelAnimationFrame(frame);frame=requestAnimationFrame(loop)}
document.addEventListener('keydown',()=>{if(world===2&&playing&&pos.y>=88)end(false)});
const isMobile=window.matchMedia('(max-width: 700px), (pointer: coarse)').matches;
let lastMobileSpawn=0;
function spawn(){if(isMobile&&performance.now()-lastMobileSpawn<700)return;if(isMobile)lastMobileSpawn=performance.now();let e=document.createElement('div');e.className=Math.random()>.45?'falling falling-corn':'falling falling-car';e.innerHTML=e.classList.contains('falling-car')?'<img src="car.png" alt="Objeto que cae">':'<img src="corn.png" alt="Objeto que cae">';game.append(e);falling.push({e,x:4+Math.random()*92,y:-12,speed:24+Math.random()*20+world2Time*1.5,spin:Math.random()*80-40})}
setInterval(()=>{if(!isMobile&&world===2&&playing){spawn();if(Math.random()>.35)spawn()}},450);
setInterval(()=>{if(isMobile)document.querySelectorAll('.falling').forEach(e=>{if(parseFloat(e.style.top)>110)e.remove()})},1000);
// Esta rama contiene únicamente el mundo 2 de Esteban.
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r'){e.preventDefault();world2()}});
world2();
function end(crash=true){playing=false;cancelAnimationFrame(frame);game.classList.remove('shaking');score=Math.max(0,score);if(world===2&&!crash){score+=10;scoreEl.textContent=score}if(score>best){best=score;localStorage.setItem('crashChickenBest',best);bestEl.textContent=best}show(crash?'¡Crash!':'¡Meta alcanzada!',crash?`Conseguiste ${score} puntos.`:`¡Llegaste a salvo! +10 puntos. Total: ${score}`,world===2?'REPETIR MUNDO 2':'REINTENTAR',crash)}
let touchStart=null;
game.addEventListener('touchstart',event=>{if(event.target.closest('button')){touchStart=null;return}touchStart=event.changedTouches[0];event.preventDefault()},{passive:false});
game.addEventListener('touchend',event=>{if(!touchStart)return;if(event.target.closest('button')){touchStart=null;return}const touch=event.changedTouches[0],dx=touch.clientX-touchStart.clientX,dy=touch.clientY-touchStart.clientY;touchStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<18)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?'ArrowRight':'ArrowLeft'):(dy>0?'ArrowDown':'ArrowUp'));event.preventDefault()},{passive:false});
function move(k){if(!playing)return;let s=isMobile?14:(world===2?8:10);if(['ArrowUp','w','W'].includes(k))pos.y=Math.min(world===2?88:91,pos.y+s);if(['ArrowDown','s','S'].includes(k))pos.y=Math.max(world===2?8:4,pos.y-s);if(['ArrowLeft','a','A'].includes(k))pos.x=Math.max(4,pos.x-s);if(['ArrowRight','d','D'].includes(k))pos.x=Math.min(96,pos.x+s);if(world===2&&pos.y>=88)return end(false);draw()}
